# Colofon

This edition is an updated version of the 2018 edition. The special interest group (SIG) Digital assessment critically reviewed, supplemented and updated the edition, partly in the light of the corona crisis of 2020/2021.  

## Contributors to this revised edition:

*	Silvester Draaijer, **Vrije Universiteit**
*	Sharon Klinkenberg, **Universiteit van Amsterdam**
*	Vincent Hendriks, **Open Universiteit**
*	Annette Peet, **SURF**

## The original publication was written by:

* Silvester Draaijer, **Vrije Universiteit**
* Jenny de Werk, **SURFnet**

### Editor

* Marjolein van Trigt

## In close collaboration with various item bank experts:

*	Sander Schenk, **Hogeschool Rotterdam**
*	Jane Groenendijk, **Prove2Move**
*	Jeroen Donkers, **Maastricht University**
*	Marjolein Wijnker, **DAS**
*	Peter Roos, **10voordeleraar**
*	Angela Verschoor, **CITO**
*	Wil de Groot-Bolluijt, **GrootBolwerk**

## With thanks to

* Desiree Joosten-Ten Brinke, **Fontys Hogescholen**
* Ludo van Meeuwen, **Technische Universiteit Eindhoven** en **SIG digitaal toetsen**
* Rob Reichardt, **NHL Stenden Hogeschool** en **SIG digitaal toetsen**
* Kirsten Veelo, **SURFnet**

## Formatting 

* Rochelle Hurenkamp, **Werkgroep Toetsen op Afstand**

## English translation 

* [Chris Hopley](https://www.chrishopley.nl/)

## Copyright

Available under the [Creative Commons Attribution 4.0 Netherlands License](https://creativecommons.org/licenses/by/4.0/deed.nl)

# Literature